# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0014_auto_20170801_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_origins',
            field=models.TextField(default='', blank=True, verbose_name='Allowed IP addresses (one per line)'),
        ),
    ]
