# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 11:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0015_auto_20171020_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='context_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Context'),
        ),
    ]
