# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0016_auto_20171030_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='from_email',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='From email'),
        ),
    ]
